version: '3.2'

services:
   db:
      image: mysql:8.0.1
      container_name: mysql-database
      restart: always
      ports:
       - '6603:3306'
      command: --init-file /data/application/init.sql
      volumes:
        - ./test-db-init.sql:/data/application/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: testtest

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8040:80'
      environment:
        PMA_HOST: db